(function () {
    'use strict';

    function buildBadWordSet(badWordsJson) {
        const normalized = new Set(); // alphanumeric-normalized words
        const raw = new Set();        // literal patterns like [_], [ __ ] kept as-is

        for (const category of Object.values(badWordsJson)) {
            for (const w of category) {
                const n = normalize(w);
                if (n.length > 0) {
                    normalized.add(n);
                } else {
                    // Normalizes to empty — keep as lowercased raw pattern
                    raw.add(w.toLowerCase().trim());
                }
            }
        }
        return { normalized, raw };
    }

    function coalescePlaceholders(captionWords) {
        // Load-bearing only for the XML fallback path: the XML tokenizer splits
        // "[ __ ]" into three tokens ([, __, ]). json3 keeps the censor token whole
        // (parseJson3 emits a single "[__]"), so this is a no-op there.
        // Merge any run of tokens that together form [ _+ ] into one token spanning the full run.
        const result = [];
        let i = 0;
        while (i < captionWords.length) {
            const w = captionWords[i].word.trim();
            // Detect start of a [ __ ] sequence
            if (w === '[') {
                let j = i + 1;
                // Collect underscore tokens
                while (j < captionWords.length && /^_+$/.test(captionWords[j].word.trim())) j++;
                // Expect closing ]
                if (j < captionWords.length && captionWords[j].word.trim() === ']') {
                    result.push({
                        word: '[__]',
                        startMs: captionWords[i].startMs,
                        endMs: captionWords[j].endMs,
                    });
                    i = j + 1;
                    continue;
                }
            }
            result.push(captionWords[i]);
            i++;
        }
        return result;
    }

    // YouTube's auto-generated (ASR) captions timestamp a word only once the
    // recognizer has heard enough of it to transcribe it, so caption times
    // consistently trail the actual audio by a couple hundred ms. Pull the mute
    // window's start earlier (and pad the end slightly) to compensate, so the
    // mute lands on the word instead of just after it. Manually-authored
    // captions are properly synced to the audio, so no lead-in is needed there.
    // With json3 word-level timing the large lead-in that compensated for XML
    // interpolation drift is no longer needed. Keep 300ms though: the muter's
    // primary driver is the ~4Hz 'timeupdate' event (rAF is suspended in a
    // backgrounded tab), so a lead-in below ~250ms would leak a swear's first
    // syllable during background playback. Over-muting a syllable of the prior
    // clean word is a far better failure mode than leaking profanity.
    const ASR_LEAD_MS = 300;
    const ASR_TRAIL_MS = 150;

    function buildMuteSchedule(rawCaptionWords, badWordSet, { isAutoGenerated = true } = {}) {
        const leadMs = isAutoGenerated ? ASR_LEAD_MS : 0;
        const trailMs = isAutoGenerated ? ASR_TRAIL_MS : 0;

        // YouTube's auto-generated caption segments frequently overlap (rolling
        // caption windows), so word order as received isn't reliably chronological.
        // Sort first so "next word" logic below is meaningful.
        const captionWords = coalescePlaceholders(rawCaptionWords)
            .slice()
            .sort((a, b) => a.startMs - b.startMs);
        const intervals = [];
        const matched = [];

        for (let i = 0; i < captionWords.length; i++) {
            const { word, startMs, endMs } = captionWords[i];
            const n = normalize(word);
            const r = word.toLowerCase().trim();
            // [__] (coalesced placeholder) or any __+ token = always mute
            const isCensoredPlaceholder = r === '[__]' || /^_+$/.test(r);
            const isBad = isCensoredPlaceholder
                || (n.length > 0 && badWordSet.normalized.has(n))
                || badWordSet.raw.has(r);

            if (isBad) {
                matched.push(word);
                // Mute from this word's start to the next word's start (or this word's end if last).
                // Clamp to the word's own endMs so overlapping/out-of-order segments can never
                // produce an inverted (endMs < startMs) interval that silently fails to mute.
                const nextStartMs = (i + 1 < captionWords.length) ? captionWords[i + 1].startMs : endMs;
                intervals.push({
                    startMs: Math.max(0, startMs - leadMs),
                    endMs: Math.max(endMs, nextStartMs) + trailMs,
                });
            }
        }
        if (matched.length) console.log('[ProfanityMuter] Matched words:', matched);
        else console.log('[ProfanityMuter] No bad words matched in transcript');
        // Log unique tokens that contain brackets/underscores to help diagnose global patterns
        const suspectTokens = [...new Set(captionWords.map(w => w.word).filter(w => /[\[_\]]/.test(w)))];
        if (suspectTokens.length) console.log('[ProfanityMuter] Bracket/underscore tokens in transcript:', suspectTokens);

        return mergeIntervals(intervals);
    }

    function normalize(word) {
        return word.toLowerCase().replace(/^[^a-z0-9]+|[^a-z0-9]+$/g, '');
    }

    function mergeIntervals(intervals) {
        if (intervals.length === 0) return [];
        intervals.sort((a, b) => a.startMs - b.startMs);

        const merged = [{ ...intervals[0] }];
        for (let i = 1; i < intervals.length; i++) {
            const last = merged[merged.length - 1];
            const cur = intervals[i];
            if (cur.startMs <= last.endMs) {
                last.endMs = Math.max(last.endMs, cur.endMs);
            } else {
                merged.push({ ...cur });
            }
        }
        return merged;
    }

    window.ProfanityMuter = window.ProfanityMuter || {};
    window.ProfanityMuter.buildBadWordSet = buildBadWordSet;
    window.ProfanityMuter.buildMuteSchedule = buildMuteSchedule;
})();
